### ISSUE TITLE
Wrong typed returned

### ISSUE THREAD

**Issue by juliusdelta** [juliusdelta/rust-rocket-api#1]
In [this branch, movie-struct](https://github.com/juliusdelta/rust-rocket-api/tree/movie-struct) I keep getting these compiler errors

```rust
error[E0308]: match arms have incompatible types
  --> src/main.rs:41:5
   |
41 | /     match movie {
42 | |         Ok(value) => Json(value),
43 | |         Err(e) => println!("{}", e),
44 | |     }
   | |_____^ expected enum `std::result::Result`, found struct `rocket_contrib::Json`
   |
   = note: expected type `std::result::Result<rocket_contrib::Json<_>, &'static str>`
              found type `rocket_contrib::Json<_>`
note: match arm with an incompatible type
  --> src/main.rs:42:22
   |
42 |         Ok(value) => Json(value),
   |                      ^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `rust-rocket-api`.
```

[This is the code in question](https://github.com/juliusdelta/rust-rocket-api/blob/movie-struct/src/main.rs#L37-L45)

I'm fairly certain I'm returning the right type, I even tried it returning just the Json movie struct instead of a `Result` and still no luck. 

I'm declaring the type that `movie` and `conn` should be returning which seems neccessary but I don't _think_ rust requires Results to be explicitly defined. If I take it out though I get an interesting compiler error:

```rust
error[E0308]: match arms have incompatible types
  --> src/main.rs:41:5
   |
41 | /     match movie {
42 | |         Ok(value) => Json(value),
43 | |         Err(e) => println!("{}", e),
44 | |     }
   | |_____^ expected enum `std::result::Result`, found struct `rocket_contrib::Json`
   |
   = note: expected type `std::result::Result<rocket_contrib::Json<_>, &'static str>`
              found type `rocket_contrib::Json<_>`
note: match arm with an incompatible type
  --> src/main.rs:42:22
   |
42 |         Ok(value) => Json(value),
   |                      ^^^^^^^^^^^

error: aborting due to previous error
```

Any thoughts? @bdougie

### Things tried:

* I first tried `get_movie` without returning a Result, but instead returning just the Json movie struct, however I got an error very similar. It stated expected type was `rocket::contrib::Json` and it got `()`

**Code:**
```rust
#[get("/<id>", format = "application/json")]
fn get<'a>(id: i32) -> Json<Movie> {
    let conn: PgConnection = establish_connection();
    let movie: Result<Movie, diesel::result::Error> = movie::get_movie(&conn, id);
    match movie { 
        Ok(value) => Json(value),
        Err(e) => println!("{}", e),
    }
}
```

* I tried returning a `Result` since my `get_movie` function returns a `Result`. I still got the same compiler error though which is strange. I haven't figured out if I **need** to return a result, but since `get_movie` can return a Struct or Err, I figured I'd try it.

* I made sure I was passing in a reference to the variable `conn` which _should_ return a `PgConnection` struct, in order for me to pass that into `get_movie`. Diesel is anticipating a reference here, not ownership of PgConnection, which is strange to me.

**Comment by bdougie** [comment]
Not quite following the wehre the `value` comes into play with `Json(value)`

My initial thought is that what is being returned from your `get` is JSON and you are looking for a `Result`

I am cloning now to see this locally play around with.

**Comment by juliusdelta** [comment]
`value` is what's being returned in the `Ok()` "block" since I'm returning a `Result` type. [Rust Docs](https://doc.rust-lang.org/std/result/)

**Comment by bdougie** [comment]
Do you have reproduction steps for how I can see this error locally? I haven't use Diesel yet, is there a CLI.I ran `cargo run` and did not see an error. 

Its been awhile since we talked about this project as well. Is there a database seeding command?

**Comment by juliusdelta** [comment]
The [ReadMe](https://github.com/juliusdelta/rust-rocket-api/blob/master/README.md) has been updated. There isn't currently a seeding command yet, my main priority was to get rocket and diesel talking and the server running, then handling data.

**Comment by juliusdelta** [comment]
I managed to figure it out.

```
#[get("/<id>", format = "application/json")]
fn get(id: i32) -> Result<Json<Movie>, diesel::result::Error> {
    let conn: PgConnection = establish_connection();
    let movie = movie::get_movie(&conn, id)?;
    Ok(Json(movie))
}
```

So apparently my `match` statement and declared type for `movie` weren't right. I think I understand why. The `?` at the end sort of implies that it's returning a result so it'll send an error if no ID matches.

I can probably explain in more detail tomorrow, but for now it's compiling and the server is starting. Now I need to put something in the database some how.
